
serviceAccount:
  create: true
  name: "redis"
  automountServiceAccountToken: true

#PodDistributionBudget Configuration
minAvailable: "2"
maxUnavailable: "1"

usePassword: true
password: ""

service:
  ports:
    redis: 6379
  type: ClusterIP
  labels:
    app: redis

persistence:
  enabled: true
  path: /redis/data
  storageClass: "redis"
  accessModes:
    - ReadWriteOnce
  size: 8Gi

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain

redis:
  updateStrategy:
    type: RollingUpdate
    ## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
    rollingUpdate:
      partition: 0

  useAOFPersistence: "yes"
  containerPorts:
    redis: 6379
    bus: 16379

  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  tolerations:
    - key : "dedicated"
      operator : "Equal"
      value : "redis"
      effect : "NoSchedule"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 4Gi

metrics:
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.55.0-debian-11-r2
    digest: ""
    pullPolicy: IfNotPresent
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
    #enable serviceMonitor when using Prometheus Operator
    serviceMonitor:
      enabled: true
      namespace: redis
      selector:
        app: redis

## Cluster settings
cluster:
  ## cluster.init Enable the initialization of the Redis Cluster
  init: true
  ## nodes = numberOfMasterNodes + numberOfMasterNodes * replicas
  ## The number of master nodes should always be >= 3, otherwise cluster creation will fail
  nodes: 6
  replicas: 1
